///--- The Helix Project ------------------------------------------------------------------------///
///                                                                                              ///
///   Part of the Helix Project, under the Attribution 4.0 International license (CC BY 4.0).    ///
///   You are allowed to use, modify, redistribute, and create derivative works, even for        ///
///   commercial purposes, provided that you give appropriate credit, and indicate if changes    ///
///   were made.                                                                                 ///
///                                                                                              ///
///   For more information on the license terms and requirements, please visit:                  ///
///     https://creativecommons.org/licenses/by/4.0/                                             ///
///                                                                                              ///
///   SPDX-License-Identifier: CC-BY-4.0                                                         ///
///   Copyright (c) 2024 The Helix Project (CC BY 4.0)                                           ///
///                                                                                              ///
///-------------------------------------------------------------------------------------- C++ ---///

#include <filesystem>
#include <fstream>
#include <memory>

#include "generator/include/CX-IR/CXIR.hh"
#include "generator/include/config/Gen_config.def"

std::string read_core_lib() {
    std::filesystem::path core_lib = std::filesystem::path(__FILE__).parent_path() / "core_lib.hh";
    std::ifstream         file(core_lib);

    if (!file.is_open()) {
        return "";
    }

    std::string core_lib_str((std::istreambuf_iterator<char>(file)),
                             std::istreambuf_iterator<char>());

    return std::string(core_lib_str);
}

std::string __CXIR_CODEGEN_N::CXIR::get_core() {
    std::string start =
        R"(#ifndef __HELIX_CORE_CXX__
#define __HELIX_CORE_CXX__
///*--- Helix ---*
///
///  Part of the Helix Project, under the Attribution 4.0 International license (CC BY 4.0).
///  You are allowed to use, modify, redistribute, and create derivative works, even for
///  commercial purposes, provided that you give appropriate credit, and indicate if changes
///  were made. For more information, please visit: https://creativecommons.org/licenses/by/4.0/
///
///  SPDX-License-Identifier: CC-BY-4.0
///  Copyright (c) 2024 (CC BY 4.0)
///
///  This file was generated by the Helix compiler, do not modify it directly.
///  Generated on: )" +
        std::to_string(std::chrono::system_clock::to_time_t(std::chrono::system_clock::now())) +
        R"( [unix-timestamp]
///
///*--- Helix ---*
)";

    std::string core_lib = read_core_lib();

    return start + core_lib + R"(
#endif
)";
}