[core]
core_location = ".helix"
auto_update = true

[transpiler]
target = "py"
warnings = true
verbose = false
threads = 50
optimization = 3
regex_module = "re"

[compiler]
py = "python"
c = "gcc"
cpp = "g++"
rust = "rustc"
flags_py = "-OO"
flags_cpp = "-std=c++17"
flags_c = "-std=c18"
flags_rust = "--edition=2021"

[linker]
c_cpp_include_dirs = []
rs_include_dirs = []
py_include_dirs = []
lib_dirs = []
link_static = false

[formatter]
indent_size = 4
formatter = "black"
always_format = false

[environment.env_vars]
