name: CI

on:
  pull_request:
  push:
    branches:
      - helix-compiler

concurrency:
  group: ${{ github.head_ref || github.run_id }}-${{ github.actor }}
  cancel-in-progress: true

jobs:
  x86_64-linux-release:
    timeout-minutes: 420
    runs-on: [self-hosted, Linux, x86_64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set execute permissions
        run: chmod +x .github/ci/*.sh
      - name: Install xmake
        run: |
          curl -fsSL https://xmake.io/shget.text | bash
          source ~/.xmake/profile
      - name: Build and Test
        run: sh .github/ci/x86_64-linux-release.sh
        
  aarch64-macos-release:
    runs-on: [self-hosted, macOS, aarch64]
    env:
      ARCH: "aarch64"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set execute permissions
        run: chmod +x .github/ci/*.sh
      - name: Install xmake
        run: |
          curl -fsSL https://xmake.io/shget.text | bash
          source ~/.xmake/profile
      - name: Build and Test
        run: .github/ci/aarch64-macos-release.sh

  x86_64-windows-release:
    runs-on: [self-hosted, Windows, x86_64]
    env:
      ARCH: "x86_64"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install xmake
        run: .github/ci/install_xmake.ps1
      - name: Build and Test
        run: .github/ci/x86_64-windows-release.ps1
